Pnr/bag count
US-CBP/GTAS-UI pull request #411
Opened 2020-11-04 20:55 UTC by kasimhelil

2020-11-04 22:01 UTC, gtasautumn commented on src/pages/paxDetail/pnr/PNR.js
> +  const getBagData = data => {
We need some grouping here by flight and passenger to match the display of the original. Each passenger should have one row with a count of the bags, list of bag ids, etc.
![bags_orig](https://user-images.githubusercontent.com/49160279/98171942-85a90c00-1ebe-11eb-87b4-ccf2b9638360.JPG)

This grouping is cleaner than having the passenger and total bag count repeated for each bag.

2020-11-04 22:04 UTC, gtasautumn requested changes
pls add the passenger grouping

2020-11-04 22:16 UTC, kasimhelil commented on src/pages/paxDetail/pnr/PNR.js
> +  const getBagData = data => {
- I didn't see the group by flight on my local; time to change my data!!!
- The reason I did't concatenate the bagIds was that the row would look clean. I will change that, Thanks!

2020-11-05 00:45 UTC, gtasautumn commented on src/pages/paxDetail/pnr/PNR.js
> +  const getBagData = data => {
no worries. I saw the same thing and checked in a little pr to give the cards more space.

2020-11-09 16:30 UTC, gtasautumn requested changes
Can you double-check the summation under bag count and total bag weight? The bag count sum at the flight level is greater than the  the numbers for the individual records. Also the total bag weight doesn't match what is displayed in the 8080 page.

2020-11-09 18:42 UTC, kasimhelil commented
> Can you double-check the summation under bag count and total bag weight? The bag count sum at the flight level is greater than the the numbers for the individual records. Also the total bag weight doesn't match what is displayed in the 8080 page.

- I am a little confused with the count that the backend is returning. Each bag has a bag count, and I thought it was the total bag count associated with a passenger in a single flight or booking details. So, if I see 3 bagIds per passenger, the count should be 3. However,  this is not what I am getting. Probably, I am using a bad data. 

And the total bag weight on 8080 site is wrong, I think.

2020-11-09 19:20 UTC, gtasautumn commented
I think the issue with the count is that it's returning you the sum on each row, so you don't need to aggregate it there. The bag weight is correct on the old site according to the database. Looks like some of hte numbers are being multiplied by the number of bags.
![pnrbagsnew](https://user-images.githubusercontent.com/49160279/98586309-87941600-2296-11eb-8350-11b38cfb20e4.JPG)
![pnrbagsold](https://user-images.githubusercontent.com/49160279/98586310-87941600-2296-11eb-97c5-559385ece51e.JPG)

2020-11-12 19:05 UTC, merged