Add more hit categories to flight pax
US-CBP/GTAS-UI pull request #464
Opened 2020-11-10 22:28 UTC by tjwdev

Sister front-end PR to "add_more_hitCategories_to_flightPax" on GTAS repo.
resolves #402 

outstanding issue: need to organize aggregate flags to space appropriately into their "columns" if alone.

2020-11-13 01:30 UTC, gtasautumn commented
Couple of things. We are not counting all hit types the same everywhere. I have a flight that shows 2 hits on the Flights page:
![hitsflight](https://user-images.githubusercontent.com/49160279/99016164-7b24ed00-2524-11eb-96e3-29e77ee3db37.JPG)

But when you click to **flightpax**, it shows there are 3 hits on the **All** tab (2 are rules and one is manual):
![hitsflightpaxall](https://user-images.githubusercontent.com/49160279/99016204-97c12500-2524-11eb-9045-e663df4588f9.JPG)

Then on the **flightpax Hits** tab, the manual hit disappears
![hitsflightpaxhits](https://user-images.githubusercontent.com/49160279/99016264-b7f0e400-2524-11eb-8152-132d99b849c5.JPG)


We need to fix:
- **FlightPax** hit counts must match between the **All** and **Hits** tabs
- Hits on the **FlightPax** page should match those on the **Flights** page
- **Flights** page **All** tab needs the same aggregation structure as the **FlightPax** page

2020-11-13 01:32 UTC, gtasautumn requested changes
FlightPax hit counts must match between the All and Hits tabs
Hits on the FlightPax page should match those on the Flights page
Flights page All tab needs the same aggregation structure as the FlightPax page

2020-11-13 01:55 UTC, gtasautumn commented on src/pages/flightPax/FlightPax.js
> +      item.hitCounts = `${item.lowPrioHitCount || 0}${item.medPrioHitCount ||
hitCounts is the structure I talked about that supports sorting the severity counts by place value.  We display the data from aggregateHitsCount as before, but use hitCounts as the accessor.

2020-11-16 06:18 UTC, tjwdev commented
Adding same aggregrate structure for flights will require more changes to other tables that I think I am wary of doing. Flights do not have direct access to the hits like Passengers do, and I do have a thought on how we can do it, by attaching the priority count to the existing flight_hit_<hit-type> tables,  but wanted it to run by people first. Otherwise, flights/flightpax with the latest push now both SHOULD count and display the same numbers AND types of hits.

2020-11-19 12:40 UTC, gtasautumn commented on src/pages/flights/Flights.js
> +        low: item.highPrioHitCount,
this looks backward. Actually, it's backward on line 60 as well. I think the lows were showing up with the red color and severe ones were yellow. Meant to fix that earlier.

2020-12-01 13:48 UTC, gtasautumn commented
For the same flight, I created a manual hit on a passengers and a watchlist hit on a third:
- Both flights tabs show the expected results
- FlightPax All tab shows the expected results
- **FlightPax Hits shows only the watchlist hits passenger. The manual hit passengers do not appear**
- **FlightPax Hits watchlist passenger has 3 hits shown when there are only 2 (doc and passenger wl hits)**

![fpaxall](https://user-images.githubusercontent.com/49160279/100748679-9d868980-33b1-11eb-913d-07aba2f39b7d.JPG)

![fpaxhits](https://user-images.githubusercontent.com/49160279/100748680-9e1f2000-33b1-11eb-8080-44e929121f6e.JPG)

![paxdetailhits](https://user-images.githubusercontent.com/49160279/100748681-9e1f2000-33b1-11eb-860d-3db0ed31f52e.JPG)

2020-12-01 18:03 UTC, tjwdev commented
Newest backend/frontend commits should resolve current counting problems.

2020-12-01 19:21 UTC, gtasautumn commented
watchlist hits still don't match on the flightpax tabs.

2020-12-02 03:44 UTC, merged