Feat/tool tips
US-CBP/GTAS-UI pull request #646
Opened 2021-02-11 19:37 UTC by tjwdev

Fixes #143

2021-02-12 00:02 UTC, kasimhelil commented on src/components/tooltipWrapper/TooltipWrapper.js
> +                    setToolTipVal(type.title);
You should use `break` once the value is found; otherwise it will continue checking all elements of the array. 
Or use `find` method instead.
`const type = asArray(types).find(t => t.value === val);
      setToolTipVal(type.title);`

2021-02-12 00:07 UTC, kasimhelil reviewed
on pax details side nave:
- `nationality` needs a tooltip 
-  the stepper labels need tooltip 
It looks good to me otherwise.

2021-02-17 01:02 UTC, gtasautumn commented on src/components/tooltipWrapper/TooltipWrapper.js
> +        getCachedKeyValues(codeType).then(types => {
This method (getCachedKeyValues) is problematic here. It's pinging the database for updates every time you hover over a link, for one. The other issue is that it's _expensive_. Locally I am seeing cpu spikes of 30% on each hover for country codes, and I got one over 90% for carriers.

Otherwise it works quite nicely. I think we should merge this one as it is, but there are some performance optimizations we should pursue in a separate ticket. I'm thinking we can either pull the required subset of matching lookup values in batch in the parent component (whichever parent fetched the data that needs tooltips) and feed that directly to the tooltip without refetching from context OR we can do it onesie-twosie but replace getCachedKeyValues with a function that only returns a single matching record. And whichever way we do it, it should probably (or maybe) not ping the db every time. We could set it to poll every minute or so in the background if we have to.

Looks good!

2021-02-17 01:07 UTC, gtasautumn commented on src/components/flightBadge/FlightBadge.js
> +      asArray(types).forEach(type => {
Here, you probably want to use array.filter or array.find. Otherwise it keeps spinning through the collection after it finds a match. ALso, remove the console.log pls.

2021-02-17 01:13 UTC, gtasautumn requested changes
Looks good but there's a wild array.foreach you should replace. see comments.

2021-02-17 01:21 UTC, gtasautumn commented on src/components/flightBadge/FlightBadge.js
> +      asArray(types).forEach(type => {
Just noticed something. Any reason we are not using the tooltip wrapper component here like elsewhere? I just realized that this code is repeated there. Then we can fix the array.foreach in tooltip wrapper and just use that component here.

2021-02-17 01:29 UTC, tjwdev commented on src/components/flightBadge/FlightBadge.js
> +      asArray(types).forEach(type => {
This was actually a hanging example when I did my first replacement after I made the tooltipwrapper. I'm actually just a dummy and missed it. Thank you for catching it! I'll change it  to use the component as I'd intended hah!

2021-02-17 14:58 UTC, gtasautumn approved these changes

2021-02-17 14:59 UTC, merged